services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: mf
      POSTGRES_PASSWORD: mfpass
      POSTGRES_DB: marketflow
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
    volumes: ["redisdata:/data"]

  marketflow:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./marketflow", "--help"]
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - PG_HOST
      - PG_PORT
      - PG_USER
      - PG_PASSWORD
      - PG_DB
      - PG_SSLMODE
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PASSWORD
      - EXCHANGE1_ADDR
      - EXCHANGE2_ADDR
      - EXCHANGE3_ADDR
    working_dir: /app

volumes:
  pgdata:
  redisdata:
