FROM golang:1.24-bullseye
RUN apt-get update && apt-get install -y netcat

WORKDIR /app

COPY exchange-entrypoint.sh .

RUN chmod +x exchange-entrypoint.sh

CMD ["/app/exchange-entrypoint.sh", "40102", "exchange2"]
