server:
  port: 8080

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: marketflow
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

exchanges:
  exchange1:
    host: localhost
    port: 40101
  exchange2:
    host: localhost
    port: 40102
  exchange3:
    host: localhost
    port: 40103

testmode:
  host: localhost
  port: 40104
